### ISSUE TITLE
Kata containers cannot support static QoS class.

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1083]
# Description of problem

When a cluster is setup with `cpuManagerPolicy: static` for example with a kubeadm.yaml

```
apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/crio/crio.sock
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  RuntimeClass: true
cpuManagerPolicy: static
systemReserved:
  cpu: 500m
  memory: 256M
kubeReserved:
  cpu: 500m
  memory: 256M
---
apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
apiServerExtraArgs:
  feature-gates: RuntimeClass=true
```

POD creation fails for pods with the runtime class set to Kata with the error

```
Internal PreStartContainer hook failed: updating resources for container "php-apache" failed: Container php-apache is not running
```

# Expected result

POD creation should work.

# Actual result

POD creation fails
