### ISSUE TITLE
Firecracker: Failed to connect to firecrackerinstance (timeout 10s)

### ISSUE THREAD

**Issue by GeorgeMac** [kata-containers/runtime#1123]
# Description of problem

I understand this is early stages for firecracker support. So I hope this just aids in smoothing over some cracks or documentation. I am having issues getting it booted based using the current directions here https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support

I am seeing this:

```
$ docker run --runtime=kata -itd --name=oh-sweet alpine sh
f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71
docker: Error response from daemon: OCI runtime create failed: Failed to connect to firecrackerinstance (timeout 10s): Get http://localhost/: dial unix /run/vc/sbs/f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71/firecracker.sock: connect: connection refused: unknown.
```

I'm certain I am just misconfiguring something. 🙇

# Expected result

I enter a shell within the alpine container.

# Actual result

I get a timeout on the firecracker domain socket.

---

# Meta details

Running `kata-collect-data.sh` version `1.5.0-rc2 (commit b954eecad14de13e09dfab89a8b902f1cb05a041)` at `2019-01-12.13:19:18.603839761+0000`.

---

Runtime is `/opt/kata/bin/kata-runtime`.

# `kata-env`

Output of "`/opt/kata/bin/kata-runtime kata-env`":
```toml
[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = false
  Trace = false
  DisableNewNetNs = false
  Path = "/opt/kata/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.5.0-rc2"
    Commit = "b954eecad14de13e09dfab89a8b902f1cb05a041"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/opt/kata/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = ""
  Version = "firecracker 0.11.0"
  Path = "/opt/kata/bin/firecracker"
  BlockDeviceDriver = "virtio-mmio"
  EntropySource = "/dev/urandom"
  Msize9p = 0
  MemorySlots = 10
  Debug = false
  UseVSock = true

[Image]
  Path = "/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.5.0-rc2_agent_91a87bc7176.img"

[Kernel]
  Path = "/opt/kata/share/kata-containers/vmlinux-4.14.67-20"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "noProxy"
  Version = ""
  Path = ""
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.5.0-rc2-4138b29661d044a298924ba60c5fd79a8b213862"
  Path = "/opt/kata/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.15.0-15-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz"

[Netmon]
  Version = "<<unknown>>"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```

---

# Runtime config files

## Runtime default config files

```
/etc/kata-containers/configuration.toml
/usr/share/defaults/kata-containers/configuration.toml
```

## Runtime config file contents

Config file `/etc/kata-containers/configuration.toml` not found
Output of "`cat "/opt/kata/share/defaults/kata-containers/configuration.toml"`":
```toml
# Copyright (c) 2017-2018 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#

[hypervisor.firecracker]
path = "/opt/kata/bin/firecracker"
kernel = "/opt/kata/share/kata-containers/vmlinux.container"
image = "/opt/kata/share/kata-containers/kata-containers.img"
kernel_params = ""
default_vcpus = 1
default_memory = 2048
default_maxvcpus = 0
default_bridges = 1
block_device_driver = "virtio-mmio"
disable_block_device_use = false
#enable_debug = true
use_vsock = true

[factory]

[proxy.kata]

[shim.kata]
path = "/opt/kata/libexec/kata-containers/kata-shim"
#enable_debug = true

[agent.kata]

[runtime]
#enable_debug = true
# If enabled, the runtime will create opentracing.io traces and spans.
# (See https://www.jaegertracing.io/docs/getting-started).
# (default: disabled)
#enable_tracing = true
internetworking_model="tcfilter"
```
Config file `/usr/share/defaults/kata-containers/configuration.toml` not found

---

# KSM throttler

## version

find: ‘/usr/libexec’: No such file or directory
Output of "` --version`":
```
/opt/kata/bin/kata-collect-data.sh: line 168: --version: command not found
```

## systemd service

# Image details

```yaml
---
osbuilder:
  url: "https://github.com/kata-containers/osbuilder"
  version: "unknown"
rootfs-creation-time: "2018-12-21T22:02:41.268658694+0000Z"
description: "osbuilder rootfs"
file-format-version: "0.0.2"
architecture: "x86_64"
base-distro:
  name: "Clear"
  version: "26850"
  packages:
    default:
      - "iptables-bin"
      - "libudev0-shim"
      - "systemd"
    extra:

agent:
  url: "https://github.com/kata-containers/agent"
  name: "kata-agent"
  version: "1.5.0-rc2-91a87bc7176750eee2f032aa564e8b28f4ad0e73"
  agent-is-init-daemon: "no"
```

---

# Initrd details

No initrd

---

# Logfiles

## Runtime logs

Recent runtime problems found in system journal:
```
time="2019-01-12T12:48:15.303769821Z" level=info msg="No info could be fetched" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd error="open /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/hypervisor.json: no such file or directory" function=init name=kata-runtime pid=16367 source=virtcontainers subsystem=firecracker
time="2019-01-12T12:48:15.311316099Z" level=warning msg="fetch sandbox device failed" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd error="open /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/devices.json: no such file or directory" name=kata-runtime pid=16367 sandbox=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd sandboxid=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd source=virtcontainers subsystem=sandbox
time="2019-01-12T12:48:26.576229264Z" level=error msg="Failed to connect to firecrackerinstance (timeout 10s): Get http://localhost/: dial unix /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/firecracker.sock: connect: connection refused" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd name=kata-runtime pid=16367 source=runtime
time="2019-01-12T12:49:22.149452349Z" level=info msg="No info could be fetched" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd error="open /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/hypervisor.json: no such file or directory" function=init name=kata-runtime pid=16612 source=virtcontainers subsystem=firecracker
time="2019-01-12T12:49:22.155545213Z" level=warning msg="fetch sandbox device failed" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd error="open /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/devices.json: no such file or directory" name=kata-runtime pid=16612 sandbox=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd sandboxid=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd source=virtcontainers subsystem=sandbox
time="2019-01-12T12:49:33.323916131Z" level=error msg="Failed to connect to firecrackerinstance (timeout 10s): Get http://localhost/: dial unix /run/vc/sbs/f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd/firecracker.sock: connect: connection refused" arch=amd64 command=create container=f6ea9afa925fbfa3a606db0ff7a92631e1e7755c4a96560366ee7f808f6defcd name=kata-runtime pid=16612 source=runtime
time="2019-01-12T13:15:10.261151475Z" level=info msg="No info could be fetched" arch=amd64 command=create container=f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71 error="open /run/vc/sbs/f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71/hypervisor.json: no such file or directory" function=init name=kata-runtime pid=17153 source=virtcontainers subsystem=firecracker
time="2019-01-12T13:15:10.267622108Z" level=warning msg="fetch sandbox device failed" arch=amd64 command=create container=f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71 error="open /run/vc/sbs/f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71/devices.json: no such file or directory" name=kata-runtime pid=17153 sandbox=f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71 sandboxid=f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71 source=virtcontainers subsystem=sandbox
time="2019-01-12T13:15:21.435028659Z" level=error msg="Failed to connect to firecrackerinstance (timeout 10s): Get http://localhost/: dial unix /run/vc/sbs/f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71/firecracker.sock: connect: connection refused" arch=amd64 command=create container=f9f2beda89250c48a7bf4679ed8688f16f49f4c0ba26aafc79db98be3fe8ea71 name=kata-runtime pid=17153 source=runtime
```

## Proxy logs

No recent proxy problems found in system journal.

## Shim logs

No recent shim problems found in system journal.

## Throttler logs

No recent throttler problems found in system journal.

---

# Container manager details

Have `docker`

## Docker

Output of "`docker version`":
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```
Output of "`docker info`":
```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.1-ce
Storage Driver: devicemapper
 Pool Name: docker-8:3-1048827-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Udev Sync Supported: true
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 312.6MB
 Data Space Total: 107.4GB
 Data Space Available: 71.32GB
 Metadata Space Used: 798.7kB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.147GB
 Thin Pool Minimum Free Space: 10.74GB
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: kata runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-15-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.778GiB
Name: sandbox
ID: GXKL:ZDJE:Q72A:VFH7:RIER:R4N6:DS24:RL6Q:CQJW:SZWO:FQWJ:3P7G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
WARNING: No swap limit support
```
Output of "`systemctl show docker`":
```
Type=notify
Restart=on-failure
NotifyAccess=main
RestartUSec=100ms
TimeoutStartUSec=infinity
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestamp=Sat 2019-01-12 12:45:23 UTC
WatchdogTimestampMonotonic=2250228729
FailureAction=none
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=15911
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
ExecMainStartTimestamp=Sat 2019-01-12 12:45:23 UTC
ExecMainStartTimestampMonotonic=2249600749
ExecMainExitTimestampMonotonic=0
ExecMainPID=15911
ExecMainCode=0
ExecMainStatus=0
ExecStart={ path=/usr/bin/dockerd ; argv[]=/usr/bin/dockerd -H fd:// ; ignore_errors=no ; start_time=[Sat 2019-01-12 12:45:23 UTC] ; stop_time=[n/a] ; pid=15911 ; code=(null) ; status=0/0 }
ExecReload={ path=/bin/kill ; argv[]=/bin/kill -s HUP $MAINPID ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
ControlGroup=/system.slice/docker.service
MemoryCurrent=115720192
CPUUsageNSec=19077003412
TasksCurrent=38
Delegate=yes
CPUAccounting=no
CPUShares=18446744073709551615
StartupCPUShares=18446744073709551615
CPUQuotaPerSecUSec=infinity
BlockIOAccounting=no
BlockIOWeight=18446744073709551615
StartupBlockIOWeight=18446744073709551615
MemoryAccounting=no
MemoryLimit=18446744073709551615
DevicePolicy=auto
TasksAccounting=no
TasksMax=18446744073709551615
UMask=0022
LimitCPU=18446744073709551615
LimitCPUSoft=18446744073709551615
LimitFSIZE=18446744073709551615
LimitFSIZESoft=18446744073709551615
LimitDATA=18446744073709551615
LimitDATASoft=18446744073709551615
LimitSTACK=18446744073709551615
LimitSTACKSoft=8388608
LimitCORE=18446744073709551615
LimitCORESoft=18446744073709551615
LimitRSS=18446744073709551615
LimitRSSSoft=18446744073709551615
LimitNOFILE=1048576
LimitNOFILESoft=1048576
LimitAS=18446744073709551615
LimitASSoft=18446744073709551615
LimitNPROC=18446744073709551615
LimitNPROCSoft=18446744073709551615
LimitMEMLOCK=65536
LimitMEMLOCKSoft=65536
LimitLOCKS=18446744073709551615
LimitLOCKSSoft=18446744073709551615
LimitSIGPENDING=31773
LimitSIGPENDINGSoft=31773
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=18446744073709551615
LimitRTTIMESoft=18446744073709551615
OOMScoreAdjust=0
Nice=0
IOScheduling=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
SecureBits=0
CapabilityBoundingSet=18446744073709551615
AmbientCapabilities=0
MountFlags=0
PrivateTmp=no
PrivateNetwork=no
PrivateDevices=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
RuntimeDirectoryMode=0755
KillMode=process
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=docker.service
Names=docker.service
Requires=docker.socket sysinit.target system.slice
Wants=network-online.target
WantedBy=multi-user.target
ConsistsOf=docker.socket
Conflicts=shutdown.target
Before=multi-user.target shutdown.target
After=firewalld.service sysinit.target network-online.target docker.socket basic.target systemd-journald.socket system.slice
TriggeredBy=docker.socket
Documentation=https://docs.docker.com
Description=Docker Application Container Engine
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/lib/systemd/system/docker.service
UnitFileState=enabled
UnitFilePreset=enabled
StateChangeTimestamp=Sat 2019-01-12 12:45:23 UTC
StateChangeTimestampMonotonic=2250228731
InactiveExitTimestamp=Sat 2019-01-12 12:45:23 UTC
InactiveExitTimestampMonotonic=2249600836
ActiveEnterTimestamp=Sat 2019-01-12 12:45:23 UTC
ActiveEnterTimestampMonotonic=2250228731
ActiveExitTimestamp=Sat 2019-01-12 12:45:22 UTC
ActiveExitTimestampMonotonic=2248532189
InactiveEnterTimestamp=Sat 2019-01-12 12:45:23 UTC
InactiveEnterTimestampMonotonic=2249589307
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Sat 2019-01-12 12:45:23 UTC
ConditionTimestampMonotonic=2249599077
AssertTimestamp=Sat 2019-01-12 12:45:23 UTC
AssertTimestampMonotonic=2249599077
Transient=no
StartLimitInterval=60000000
StartLimitBurst=3
StartLimitAction=none
```
No `kubectl`

---

# Packages

Have `dpkg`
Output of "`dpkg -l|egrep "(cc-oci-runtimecc-runtimerunv|kata-proxy|kata-runtime|kata-shim|kata-ksm-throttler|kata-containers-image|linux-container|qemu-)"`":
```
ii  qemu-block-extra:amd64              1:2.5+dfsg-5ubuntu10.33               amd64        extra block backend modules for qemu-system and qemu-utils
ii  qemu-kvm                            1:2.5+dfsg-5ubuntu10.33               amd64        QEMU Full virtualization
ii  qemu-system-common                  1:2.5+dfsg-5ubuntu10.33               amd64        QEMU full system emulation binaries (common files)
ii  qemu-system-x86                     1:2.5+dfsg-5ubuntu10.33               amd64        QEMU full system emulation binaries (x86)
ii  qemu-utils                          1:2.5+dfsg-5ubuntu10.33               amd64        QEMU utilities
```
No `rpm`

---
