### ISSUE TITLE
use_vsock=true gives context deadline exceeded error with ubuntu bionic kernel

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#1203]
Setting `use_vsock=true` gives the following error with 1.5.0 (packaged or static):

```
$ sudo docker run -ti --runtime kata-runtime busybox sh
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```

**Comment by jodh-intel** [comment]
I'm struggling to see how this happened given we have explicit vsock jenkins slaves in our CI:

- https://github.com/kata-containers/ci/tree/master/jenkins/jobs

It's possible though that something broke at the packaging stage? We **must** get the following setup asap to avoid any chance of that:

- https://github.com/kata-containers/ci/issues/10

**Comment by grahamwhaley** [comment]
But, then it seems to work for me. I did a fresh F28 server install today with devicemapper and only installed the kata 1.5 static tarball, and I have just run a bunch of kata-fc tests, and tried a kata-qemu as well... Here is my kata-env from the qemu:

`$ /opt/kata/bin/kata-qemu kata-env`
```toml
[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  Path = "/opt/kata/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.5.0"
    Commit = "5f7fcd773089a615b776862f92217e987f06df0a"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.2(kata-static)\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = true

[Image]
  Path = "/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.5.0_agent_a581aebf473.img"

[Kernel]
  Path = "/opt/kata/share/kata-containers/vmlinuz-4.14.67-22"
  Parameters = "init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket"

[Initrd]
  Path = ""

[Proxy]
  Type = "noProxy"
  Version = ""
  Path = ""
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.5.0-efbf3bb25065ce89099630b753d218cdc678e758"
  Path = "/opt/kata/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.16.3-301.fc28.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Fedora"
    Version = "28"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i7-6770HQ CPU @ 2.60GHz"

[Netmon]
  Version = "kata-netmon version 1.5.0"
  Path = "/opt/kata/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```

and

```bash
$ docker info --format "{{json .Runtimes}}"
{"kata-fc":{"path":"/opt/kata/bin/kata-fc"},"kata-qemu":{"path":"/opt/kata/bin/kata-qemu"},"runc":{"path":"docker-runc"}}
$ docker run --rm -ti --runtime=kata-qemu busybox sh
/ # uname -a
Linux 6f41cd0e986a 4.14.67 #1 SMP Tue Jan 22 23:49:04 CST 2019 x86_64 GNU/Linux
/ # exit
$ uname -a
Linux skull 4.16.3-301.fc28.x86_64 #1 SMP Mon Apr 23 21:59:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if you want more info, or for me to try to run something else..
