### ISSUE TITLE
aarch64: qemu: update from 3.1.0-rc2 to full 3.1.0 ?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#1258]
In the verisons.yaml, for the aarch64 qemu we have `v3.1.0-rc2` listed. I believe [v3.1.0 full](https://github.com/qemu/qemu/releases/tag/v3.1.0) is now available. Any reason to not update that @teawater ?

```yaml
   qemu:
      description: "VMM that uses KVM"
      url: "https://github.com/qemu/qemu"
      version: "stable-2.11"
      architecture:
        aarch64:
          branch: "master"
          tag: "v3.1.0-rc2"
          commit: "47c1cc30e440860aa695358f7c2dd0b9d7b53d16"
```
