### ISSUE TITLE
Longer time of nodejs execution

### ISSUE THREAD

**Issue by running99** [kata-containers/runtime#1274]
# Description of problem

node-v10.15.1: https://nodejs.org/dist/v10.15.1/node-v10.15.1-linux-x64.tar.xz

```
docker run -it -d --runtime kata-runtime -v /node-v10.15.1-linux-x64:/node-v10.15.1-linux-x64 --name kata ubuntu
docker exec -it kata bash
root@598abbe6c7cf:/# cat > a.js <<EOF
const fs = require('fs');
EOF
root@598abbe6c7cf:/# time /node-v10.15.1-linux-x64/bin/node a.js
real 0m0.318s
user 0m0.098s
sys  0m0.049s
```

```
docker run -it -d --runtime runc -v /node-v10.15.1-linux-x64:/node-v10.15.1-linux-x64 --name runc ubuntu
...
# time /node-v10.15.1-linux-x64/bin/node a.js
real 0m0.105s
user 0m0.084s
sys  0m0.020s
```

# Expected result

Is there some way to speed up execution?

# Actual result

(replace this text with details of what actually happened)

- Running kata-containers/tests/blob/master/metrics/storage/fio.sh

| type | blocksize | key | runc | kata |
|-|-|-|-|-|
| randread | 4k | bw | 11611 | 21724|
||| iops | 2902 | 5431|
||| lat_ns(mean) | 5506034 | 2937049|
| randread | 8k | bw | 46755 | 25743|
||| iops | 5844 | 3217|
||| lat_ns(mean) | 2735484 | 4962878|
| randread | 16k | bw | 107182 | 36334|
||| iops | 6698 | 2270|
||| lat_ns(mean) | 2387397 | 7035435|
| randread | 32k | bw | 121125 | 29335|
||| iops | 3785 | 916|
||| lat_ns(mean) | 4225229 | 17444117|
| randread | 64k | bw | 122847 | 30645|
||| iops | 1919 | 478|
||| lat_ns(mean) | 8331971 | 33400848|

---

# Meta details

Running `kata-collect-data.sh` version `1.5.0 (commit 5f7fcd7)` at `2019-02-22.18:19:11.949501327+0800`.

---

Runtime is `/usr/bin/kata-runtime`.

# `kata-env`

Output of "`/usr/bin/kata-runtime kata-env`":
```toml
[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.5.0"
    Commit = "5f7fcd7"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.5.0_agent_a581aebf473.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67.22-18.container"
  Parameters = "init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.5.0-9e77a0b"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.5.0-efbf3bb"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.9.0-6-amd64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Debian GNU/Linux"
    Version = "9"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz"

[Netmon]
  Version = "kata-netmon version 1.5.0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```

---

# Container manager details

Have `docker`

## Docker

Output of "`docker version`":
```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```
---
# Packages

Have `dpkg`
Output of "`dpkg -l|egrep "(cc-oci-runtimecc-runtimerunv|kata-proxy|kata-runtime|kata-shim|kata-ksm-throttler|kata-containers-image|linux-container|qemu-)"`":
```
ii  kata-containers-image               1.5.0-15                       amd64        Kata containers image
ii  kata-ksm-throttler                  1.5.0.git+3dd4c9f-18           amd64        
ii  kata-linux-container                4.14.67.22-18                  amd64        linux kernel optimised for container-like workloads.
ii  kata-proxy                          1.5.0+git.9e77a0b-16           amd64        
ii  kata-runtime                        1.5.0+git.5f7fcd7-24           amd64        
ii  kata-shim                           1.5.0+git.efbf3bb-14           amd64        
ii  qemu-lite                           2.11.0+git.87517afd72-19       amd64        linux kernel optimised for container-like workloads.
ii  qemu-vanilla                        2.11.2+git.0982a56a55-19       amd64        linux kernel optimised for container-like workloads.
```
No `rpm`

---
