### ISSUE TITLE
Allocated vCPUs doesn't match expectations from podspec

### ISSUE THREAD

**Issue by kennymacleod** [kata-containers/runtime#1292]
# Description of problem

Under Kata 1.5 and Kube 1.12, the number of VCPUs allocated to the pod's VM doesn't seem to correspond to the CPU resource restrictions in the pod spec. - but I only see 5.

# Expected result

For example, if I have a pod spec with 3 containers that have cpu limit of 8, 4 and none respectively, I'd expect 13 vCPUs in the pod

# Actual result

When I exec into one of the containers in the pod, and run `cat /proc/cpuinfo`, I see 5 vCPUs.

Here's my pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: log-explorer
  annotations: 
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - image: busybox:latest
    name: container1
    args:
    - sleep
    - "1000000"
    resources:
      limits:
        cpu: "8"  
  - image: busybox:latest
    name: container2
    args:
    - sleep
    - "1000000"
    resources:
      limits:
        cpu: "4"  
  - image: busybox:latest
    name: container3
    args:
    - sleep
    - "1000000"
  nodeSelector:
    customer: kata
  tolerations:
  - effect: NoSchedule
    key: customer
    operator: Equal
    value: kata    
```
