### ISSUE TITLE
Pod information left in k8s test

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1611]
1. Create resource quota
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-quota
spec:
  hard:
    pods: "2"
```
2. Create a deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymenttest
spec:
  selector:
    matchLabels:
      purpose: quota-demo
  replicas: 3
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.TrustedSandbox: "false"
        io.kubernetes.cri.untrusted-workload: "true"
      labels:
        purpose: quota-test
    spec:
      containers:
      - name: pod-quota-demo
        image: busybox
        command: ["tail", "-f", "/dev/null"]
```
Here we are specifying that the deployment will use three replicas, however, only two pods will be created because of the quota.
However, the two pods run without issues but at the moment of deleting the deployment and the resource quota even if it says that is made successfully, we have pod information left at /var/lib/vc/sbs.
