### ISSUE TITLE
Snap package shim not working with containerd

### ISSUE THREAD

**Issue by joedborg** [kata-containers/runtime#1718]
# Description of problem

Trying to connect the shim from the snap package to containerd.  Config for containerd taken from https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md

# Expected result

Be able to start containerd containers.

# Actual result

```bash
$ ln -s /snap/kata-containers/288/usr/libexec/kata-containers/kata-shim /usr/bin/containerd-shim-kata-v2  # doing this so containerd picks it up; may be wrong.

$ sudo ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh

ctr: flag provided but not defined: -namespace
Usage of /usr/bin/containerd-shim-kata-v2:
  -agent string
    	agent gRPC socket endpoint
  -agent-logs-socket string
    	socket to listen on to retrieve agent logs
  -container string
    	container id for the shim
  -debug
    	enable debug mode
  -exec-id string
    	process id for the shim
  -log string
    	set shim log level: debug, info, warn, error, fatal or panic (default "warn")
  -proxy-exit-code
    	proxy exit code of the process (default true)
  -terminal
    	specify if a terminal is setup
  -trace
    	enable opentracing support
  -version
    	display program version and exit
: exit status 2: unknown

```

---

This should be fixed too:
```bash
$ sudo /snap/kata-containers/288/usr/bin/kata-collect-data.sh 
ERROR: kata-collect-data.sh: cannot find runtime 'kata-runtime'
```

**Comment by devimc** [comment]
@joedborg thanks for raising this, but seems like you are creating a symlink to the wrong shim

you are running 

```
$ ln -s /snap/kata-containers/288/usr/libexec/kata-containers/kata-shim /usr/bin/containerd-shim-kata-v2
```

when it should be

```
$ ln -s /snap/kata-containers/288/usr/bin/containerd-shim-kata-v2 /usr/bin/containerd-shim-kata-v2
```

**Comment by devimc** [comment]
> This should be fixed too:
$ sudo /snap/kata-containers/288/usr/bin/kata-collect-data.sh 
ERROR: kata-collect-data.sh: cannot find runtime 'kata-runtime'

you're right

**Comment by joedborg** [comment]
> `$ ln -s /snap/kata-containers/288/usr/bin/containerd-shim-kata-v2 /usr/bin/containerd-shim-kata-v2`

Ah thanks @devimc, that's my bad.  I got this binary by running `kata-containers.runtime kata-env` and looking at the shim binary in there.

**Comment by joedborg** [comment]
@devimc have you any idea how to debug or fix this?

```bash
sudo ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: no such file or directory: not found
```

**Comment by devimc** [comment]
@joedborg 

try with `sudo -E PATH=$PATH ctr run....`

**Comment by joedborg** [comment]
@devimc Thanks, sadly it gives the same error.  I think it's coming from something containerd is calling (maybe the shim) rather than from ctr itself.  Could be another issue coming from being within the Snapd environment.  I did try to install via the bash script, but I get apt dependency issues.

**Comment by devimc** [comment]
@joedborg that's weird, a symlink should be enough, see https://github.com/kata-containers/packaging/blob/master/.ci/setup.sh#L59-L63

**Comment by joedborg** [comment]
@devimc I've added all those sym links, with the same error resulting.  Is anything obviously wrong?

```toml
root = "/var/lib/containerd"
state = "/run/containerd"
oom_score = 0

[grpc]
  address = "/run/containerd/containerd.sock"
  uid = 0
  gid = 0
  max_recv_message_size = 16777216
  max_send_message_size = 16777216

[debug]
  address = ""
  uid = 0
  gid = 0
  level = ""

[metrics]
  address = ""
  grpc_histogram = false

[cgroup]
  path = ""

[plugins]
  [plugins.cgroups]
    no_prometheus = false
  [plugins.cri]
    stream_server_address = "127.0.0.1"
    stream_server_port = "0"
    enable_selinux = false
    sandbox_image = "k8s.gcr.io/pause:3.1"
    stats_collect_period = 10
    systemd_cgroup = false
    enable_tls_streaming = false
    max_container_log_line_size = 16384
    [plugins.cri.containerd]
      no_pivot = false
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.runc.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "runc"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
      [plugins.cri.containerd.runtimes.kata]
         runtime_type = "io.containerd.kata.v2"
      [plugins.cri.containerd.runtimes.katacli]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.katacli.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "/usr/bin/kata-runtime"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
    [plugins.cri.registry]
      [plugins.cri.registry.mirrors]
        [plugins.cri.registry.mirrors."docker.io"]
          endpoint = ["https://registry-1.docker.io"]
      
    
    [plugins.cri.x509_key_pair_streaming]
      tls_cert_file = ""
      tls_key_file = ""
  [plugins.diff-service]
    default = ["walking"]
  [plugins.linux]
    shim = "containerd-shim"
    runtime = "runc"
    runtime_root = ""
    no_shim = false
    shim_debug = false
  [plugins.opt]
    path = "/opt/containerd"
  [plugins.restart]
    interval = "10s"
  [plugins.scheduler]
    pause_threshold = 0.02
    deletion_threshold = 0
    mutation_threshold = 100
    schedule_delay = "0s"
    startup_delay = "100ms"
```

**Comment by devimc** [comment]
@joedborg in my case the cri configuration is a little bit different

```toml
[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      [plugins.cri.containerd.runtimes.runc]
        runtime_type = "io.containerd.runtime.v1.linux"
        [plugins.cri.containerd.runtimes.runc.options]
          Runtime = "runc"
          RuntimeRoot = "/usr/sbin/runc"
      [plugins.cri.containerd.runtimes.kata]
        runtime_type = "io.containerd.runtime.v1.linux"
        [plugins.cri.containerd.runtimes.kata.options]
          Runtime = "kata-runtime"
          RuntimeRoot = "/usr/local/bin/kata-runtime"
```
