### ISSUE TITLE
hugepages in K8s with kata not working properly

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1719]
I am using `kubernetes 1.14` along with kata and when I am trying to run a pod with `hugepages` the status remain `pending` when I try to see the status of the pod
```
$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
hugepages-volume-jz9f8   0/1     Pending   0          10s
```
This is the pod.yaml that I am using
```
apiVersion: v1
kind: Pod
metadata:
  generateName: hugepages-volume-
spec:
  runtimeClassName: kata
  containers:
  - image: fedora:latest
    command:
    - sleep
    - inf
    name: example
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      limits:
        hugepages-2Mi: 100Mi
        memory: 100Mi
      requests:
        memory: 100Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
```
This is the output for `kubectl describe pods`
```
$ kubectl describe pods
Name:               hugepages-volume-jz9f8
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               <none>
Labels:             <none>
Annotations:        <none>
Status:             Pending
IP:
Containers:
  example:
    Image:      fedora:latest
    Port:       <none>
    Host Port:  <none>
    Command:
      sleep
      inf
    Limits:
      hugepages-2Mi:  100Mi
      memory:         100Mi
    Requests:
      hugepages-2Mi:  100Mi
      memory:         100Mi
    Environment:      <none>
    Mounts:
      /hugepages from hugepage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qm66f (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  hugepage:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     HugePages
    SizeLimit:  <unset>
  default-token-qm66f:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qm66f
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  17s (x2 over 17s)  default-scheduler  0/1 nodes are available: 1 Insufficient hugepages-2Mi.
```
This is the output from the host
```
$ cat /proc/meminfo | grep Huge
AnonHugePages:    372736 kB
ShmemHugePages:        0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
```
