### ISSUE TITLE
document swarm docker version more clearly

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#181]
We currently document that docker 1.12 is required for using swarm in the versions database:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L100..L106

However, that's not strictly true since "basic" swarm works:

- https://github.com/kata-containers/tests/pull/199

We need to update the versions database to clarify that somehow. I vote for adding a reference to the issue in question using a new `swarm-issue` value like this:

```
  docker:
    description: "Moby project container manager"
    notes: "Docker Swarm requires an older version of Docker."
    url: "https://github.com/moby/moby"
    version: "v17.12-ce"
    meta:
      swarm-version: "1.12.1"
      swarm-issue: "https://github.com/kata-containers/runtime/issues/175"
```
