### ISSUE TITLE
Multus CNI attempts to overwrite device name for multiple interfaces

### ISSUE THREAD

**Issue by shrmrf** [kata-containers/runtime#1811]
### Description of problem
I followed the [multus-cni/quickstart.md#what-if-i-want-more-interfaces](https://github.com/intel/multus-cni/blob/master/doc/quickstart.md#what-if-i-want-more-interfaces) guide. 

This configuration fails:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf,macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
```

### Expected result
Like a normal pod, I expected to see 2 network interfaces created (perhaps called `net1` and `net2`).

### Actual result
Pod never gets created
```
...
Events:
  Type     Reason                  Age               From                Message
  ----     ------                  ----              ----                -------
  Normal   Scheduled               59s               default-scheduler   Successfully assigned default/samplepod to kadasd620
  Warning  FailedCreatePodSandBox  2s (x8 over 52s)  kubelet, kadasd620  Failed create pod sandbox: rpc error: code = Unknown desc = container create failed: rpc error: code = Internal desc = Could not add route
 dest(192.168.1.0/24)/gw()/dev(net2): file exists
```
