### ISSUE TITLE
annotations: kata annotations not working anymore

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#2125]
cannot enable a debug console using annotations

I'm using the following yaml, custom kernel parameters are useless

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    io.kata-containers.hypervisor.kernel_params: "agent.debug_console"
spec:
  shareProcessNamespace: true
  runtimeClassName: kata
  containers:
  - name: first-test-container
    image: busybox
    command:
      - sh
    stdin: true
    tty: true
```

cc @amshinde
