### ISSUE TITLE
/dev/shm mount based on empty-dir volumes are not handled correctly.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#2631]
With https://github.com/kata-containers/runtime/pull/357, we were able to handle the docker option for `--shmsize` thats helps configure an shm size. We use a shared shm mount that is shared across all containers in a pod. However, in case of Kubernetes, there isnt an option similar to `--shmsize` to configure the size of the shm mount. An existing pattern is to use an an empty-dir volume for the shm mount, allowing a size other than the default 64KB.
```
apiVersion: v1
kind: Pod
metadata:
  name: kata-pod
spec:
  runtimeClassName: kata
  containers:
    - name: kata-shm-pod
      image: debian
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "6Gi"
          cpu: "2"
        requests:
          memory: "6Gi"
          cpu: "2"
      volumeMounts:
      - mountPath: /dev/shm
        name: shm
  volumes:
  - name: shm
    emptyDir:
      sizeLimit: "2Gi"
      medium: "Memory"
```

However, this is not handled correctly in Kata, the shm mount is still sized as 64 KB even when the shm mount is backed by tmpfs empty-dir volume.

**Comment by amshinde** [comment]
cc @thbtcllt 
I have raised #2632 to address this issue. With that PR, the shm mount for the container is now backed by tmpfs. But, we still have a limitation. Although one can specify the `sizeLimit` for an empty-dir volume, this is not really passed as a mount option by kubernetes. 

There is an existing PR in place to address this issue:
https://github.com/kubernetes/kubernetes/pull/63641/commits/9afb75ff8761bd0bb498c8bd8893aa87ecf1839d

When a tmpfs mount is created without specifying the size, the tmpfs typically is assigned a size that is half of the RAM. In case, of Kata, this will be half the size of the default memory that the VM is started with. In our configuration.toml, we have the deault memory set to 2048MB, so the tmpfs mount will get a size of half of that. If you need an shm mount greater than that, one workaround will be to start with a higher default memory for the VM. This can be done via the configuration.toml file or through an annotation as shown below.
```
apiVersion: v1
kind: Pod
metadata:
  name: kata-pod
  annotations:
    io.katacontainers.config.hypervisor.default_memory: "4096"
```

Once, the kubernetes PR is merged in a future release of k8s, we can do a a better job of accounting for the actual memory that the VM should be started with.

 @thbtcllt Let me know if the patch works out for you.
