### ISSUE TITLE
Kata does not support hostpid

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#2633]
Kubernetes provides ability for a pod to share host Pid namespace:
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces

Like so:
```
apiVersion: v1
kind: Pod
metadata:
  name: view-pid
  namespace: default
spec:
  hostPID: true
  containers:
    - name: container-view-pid
      image: alpine
      command:
        - sleep
        - "3600"
```

In Kata, we cannot really share the host Pid namespace due to VM boundary. We could potentially  translate this to sharing the pid namespace of the agent.
I am not too inclined for doing this, as this potentially opens up the agent processes. We may just choose not to implement this as list this as a limitation.
