### ISSUE TITLE
rsyslog service cannot be started in kata container

### ISSUE THREAD

**Issue by Xiaohua-Shen** [kata-containers/runtime#2699]
# Description of problem
1. start a ubuntu 16.04 container
```
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - command:
    - sleep
    - 8h
    image: ubuntu:18.04
```
2. exec into this pod and install rsyslog and start service
```
apt-get update
apt-get install rsyslog
service rsyslog start
```

# Expected result

the rsyslog should start successfully

# Actual result

the rsyslog start with error
```
# service rsyslog start
 * Starting enhanced syslogd rsyslogd      
                                                                                                                                              
 rsyslog startup failure, child did not respond within startup timeout (60 seconds)
# service rsyslog status
 * rsyslogd is not running
```

for non kata containers (without annotation ` io.kubernetes.cri.untrusted-workload: "true"`), above rsyslog can be started successfully.

# related envs
kata: 1.10
kubernetes: 1.16 with cri-containerd to run kata
