### ISSUE TITLE
shimv2+crio: openshift/k8s e2e tests fail with `failed to get parse function: unsupported log format`

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#2764]
# Description of problem
Some of the k8s/openshift e2e conformance tests are failing with the next errors:

From test `[sig-storage] EmptyDir volumes should support (non-root,0644,default) [LinuxOnly] [NodeConformance] [Conformance]`
```
Jun 10 21:43:40.855: FAIL: Unexpected error:
    <*errors.errorString | 0xc002cec110>: {
        s: "expected \"perms of file \\\"/test-volume/test-file\\\": -rw-r--r--\" in container output: Expected\n    <string>: failed to get parse function: unsupported log format: \"mount type of \\\"/test-volu
me\\\": 2035054128\\n\"\nto contain substring\n    <string>: perms of file \"/test-volume/test-file\": -rw-r--r--",
    }
    expected "perms of file \"/test-volume/test-file\": -rw-r--r--" in container output: Expected
        <string>: failed to get parse function: unsupported log format: "mount type of \"/test-volume\": 2035054128\n"
    to contain substring
        <string>: perms of file "/test-volume/test-file": -rw-r--r--
occurred
[AfterEach] [sig-storage] EmptyDir volumes
  /workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:152
```

From test `[sig-api-machinery] Secrets should be consumable via the environment [NodeConformance] [Conformance]`
```
Jun 10 22:21:15.287: INFO: Pod pod-configmaps-70d0aa97-5eab-4652-abc0-30718707da2e no longer exists
Jun 10 22:21:15.287: FAIL: Unexpected error:
    <*errors.errorString | 0xc002c955b0>: {
        s: "expected \"data_1=value-1\" in container output: Expected\n    <string>: failed to get parse function: unsupported log format: \"KUBERNETES_SERVICE_PORT=443\\n\"\nto contain substring\n    <string>:
data_1=value-1",
    }
    expected "data_1=value-1" in container output: Expected
        <string>: failed to get parse function: unsupported log format: "KUBERNETES_SERVICE_PORT=443\n"
    to contain substring
        <string>: data_1=value-1
occurred
```

## System details:
`k8s 1.17.3`
```
$ crio --version
crio version 1.17.0-dev
commit: 0eec454168e381e460b3d6de07bf50bfd9b0d082
```
kata-shimv2 of kata-runtime master branch (not 2.0, but it could also has this issue) - commit   : 9d04ea719ace4cbc1f342482c0f83b9ccfd6eabe

These kind of failures were also reproduced on an openshift cluster that @fidencio provided. 

looking at the journal of kata, I do not see anything related

**Comment by chavafg** [comment]
tried to reproduce this issue with containerd and it doesn't happen. This only happens with crio.

**Comment by evanfoster** [comment]
I'm running into this issue as well.
```
vmss-agent-kata1-test-rmuuc000000 ~ # /opt/kata/bin/kata-runtime --version
kata-runtime  : 1.12.0-alpha0
   commit   : 337f2e0c7ba5f8dff5ac46e568886a42ca56d683
   OCI specs: 1.0.1-dev

vmss-agent-kata1-test-rmuuc000000 ~ # crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.17.4
RuntimeApiVersion:  v1alpha1

vmss-agent-kata1-test-rmuuc000000 ~ # kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"archive", BuildDate:"2020-07-01T16:28:46Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

Here's an example workload that reproduces the issue for me:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: fio-test
  labels:
    role: fio-test
spec:
  nodeSelector:
    kubernetes.io/hostname: vmss-agent-kata1-test-rmuuc000000
  tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/kata-containers
      operator: Equal
      value: "true"
  containers:
    - name: fio
      image: dmonakhov/alpine-fio
      command: ["fio", "--name=random-writers-emptydir", "--filename=/test-volume/testfile", "--ioengine=libaio", "--iodepth=16", "--rw=randwrite", "--bs=512", "--direct=0", "--size=1G", "--numjobs=1", "--runtime=60s", "--group_reporting", "--fallocate=none", "--time_based", "--thread", "--invalidate=1", "--output-format=json"]
      volumeMounts:
        - name: test-volume
          mountPath: /test-volume
  restartPolicy: Never
  runtimeClassName: kata-qemu
  volumes:
    - name: test-volume
      emptyDir: {}
```
