### ISSUE TITLE
docker:dind not working in 1.11.1 qemu-virtiofs

### ISSUE THREAD

**Issue by skaegi** [kata-containers/runtime#2789]
# Description of problem
We use a kata-deploy style install for using Kata with Kubernetes (containerd 1.3.4 -- overlaysfs snapshotter) and just tried updating from 1.11.0 to 1.11.1. When using the qemu-virtiofs runtime we now cannot run docker commands and get operation not permitted errors. The errors below are using the unmodified 1.11.1 release.

# Expected result
```
(When running inside a K8 pod using kata)
docker run hello-world -- works just like it did in 1.11.0
```
# Actual result
```
/ # docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete 
Digest: sha256:d58e752213a51785838f9eed2b7a498ffa1cb3aa7f946dda11af39286c3db9a9
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"b *:* m\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/docker/81a3c5750ffe91ea0c5992f5b532589c8aa2a64cd1cb22c6a49036bf356b32e2/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/docker/81a3c5750ffe91ea0c5992f5b532589c8aa2a64cd1cb22c6a49036bf356b32e2/devices.allow: operation not permitted\\\"\"": unknown.
```
Just the error message:

> Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"process_linux.go:415: setting cgroup config for procHooks process caused \\\"failed to write \\\\\\\"b *:* m\\\\\\\" to \\\\\\\"/sys/fs/cgroup/devices/docker/81a3c5750ffe91ea0c5992f5b532589c8aa2a64cd1cb22c6a49036bf356b32e2/devices.allow\\\\\\\": write /sys/fs/cgroup/devices/docker/81a3c5750ffe91ea0c5992f5b532589c8aa2a64cd1cb22c6a49036bf356b32e2/devices.allow: operation not permitted\\\"\"": unknown.

Here is a simples pod spec to help illustrate...
```
apiVersion: v1
kind: Pod
metadata:
  name: untrusted-dind
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
    - name: docker
      image: docker:dind
      imagePullPolicy: IfNotPresent
      command:
      - dockerd-entrypoint.sh
      - dockerd
      - --host=unix:///var/run/docker.sock
      - --host=tcp://localhost:2375
      - --mtu=1400
      securityContext:
        privileged: true
      ports:
        - containerPort: 2375
```
(using untrusted annotation because runtimeClass feature gate is off in my environment)
