### ISSUE TITLE
Remove agent version from kata-env output

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#310]
The `kata-env` command currently shows the following agent details:

```
[Agent]
  Type = "kata"
  Version = "<<unknown>>"
```

The `Version` element was added for parity with the other elements whose details `kata-env` displays. However, that version is simply a static string because the runtime cannot determine the agent version *without creating a container and connecting to the agent*.

As such, let's just remove the string since:

- it never changes.
- it's potentially misleading.
- users *can* determine the agent version by running `kata-collect-data.sh`, which now shows details of the image, including something like:

```
agent:
  url: "https://github.com/kata-containers/agent"
  name: "kata-agent"
  version: "0.2.0-e444fe2bbbc57fdd47dad00f369935009b094817"
  agent-is-init-daemon: "no"

```
