### ISSUE TITLE
use kata-containers as runtime, how to run k8s pods with gpu resource

### ISSUE THREAD

**Issue by chestack** [kata-containers/runtime#3106]
# Description of problem

My cluster environment:  k8s(1.16)+containerd+kata(1.12)+nvidia-device-plugin

I would like to start k8s pods with GPU resource using the following YAML file
```
apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: kube-system
spec:
  runtimeClassName: kata
  containers:
    - name: cuda-container
      image: docker.io/nvidia/cuda:9.0-base
      command:
      - sleep
      - 7d
      resources:
        limits:
          nvidia.com/gpu: 1
```

# Expected result

Pods running correctly 

# Actual result

Pods can not start

# Further information

I have read the doc: https://github.com/kata-containers/documentation/blob/master/use-cases/Nvidia-GPU-passthrough-and-Kata.md#nvidia-gpu-pass-through-mode-with-kata-containers

From my understanding, kata to use GPU passthrough, the device driver should be vfio-pci. But k8s nvidia device plugin depends on nvidia as a device driver. So using kata as runtime how could I run k8s pods with gpu resources. Thanks a lot.
