### ISSUE TITLE
kata-runtime exe path is not included in `kata-env` output

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#577]
# Description of problem

Running `kata-runtime kata-env` gives you a bunch of useful info, but it does not tell you which `kata-runtime` exe actually got run and generated that output.

I think we can extend to add an extra `Path` entry for the runtime itself, probably using a call to https://golang.org/pkg/os/#Executable

# Expected result

I'd like to see maybe this:

```toml
[Runtime]
  Debug = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.1.0"
    Commit = "e35caa60ade78efa61160c324309e2bc6b71932c"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"
```

# Actual result

But currently we get this:

```toml
[Runtime]
  Debug = false
  [Runtime.Version]
    Semver = "1.1.0"
    Commit = "e35caa60ade78efa61160c324309e2bc6b71932c"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"
```

---
