### ISSUE TITLE
[cgroup support] How to calculate pod resources?

### ISSUE THREAD

**Issue by WeiZhang555** [kata-containers/runtime#743]
When I am developing "host cgroup" support feature for kata containers (PR: #734  , issue: #344 ) , I realized that we don't have an all-agreed policy on how to calculate POD resources, take this pod spec as an example:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx-untrusted
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: busybox
    image: busybox
    command: ['top']
```

If one container ”nginx“ has a resource limit of 128M memory and 0.5 core CPU, another container "busybox" in same POD has no resource limit(in other words, unlimited resources), how should we calculate the POD resource? 

Should we give the pod 128M and 0.5 core because this is the specified resource limit?
Or should we give each container a default resource(let's say 1 core, 128M), and calculated this as 128M+128M+128M（pause container） and 0.5core+1core+1core ?
