### ISSUE TITLE
versions: Update contaienrd version to 1.1.3

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#748]
Update to the latest released version:

```yaml
  cri-containerd:
    version: "v1.0.5"
    meta:
      containerd-version: "1.1.3"
```
