### ISSUE TITLE
list: should be more robust in the event of bad or missing containers

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#809]
# Description of problem

I ran a `kata-runtime list` on a system that had failed some containers, but rather than tell me the containers that it could ascertain, it bombed with an error and told me nothing else:

```bash
$ sudo kata-runtime list
stat /var/lib/docker/overlay2/0679ee48a27e955971302a6bf1b6c4941c58f8d3b1020b91889127265a77911f/merged: no such file or directory

$ sudo ls -lad  /var/lib/docker/overlay2/0679*
ls: cannot access '/var/lib/docker/overlay2/0679*': No such file or directory
$ sudo ls -la /var/lib/docker/overlay2 | wc
   1698   15275  192325
$ docker ps -qa | wc
    827     827   10751
$ ps -e | fgrep kata-proxy | wc
    827    3308   28945
$ ps -e | fgrep kata-shim | wc
    827    3308   28118
$ ps -e | fgrep qemu | wc
   1000    4000   40000
```

# Expected result

I'd expect `list` to probably show the containers it could find. This might be a touch tricky though - what should it do upon error? How should it report it. Will that upset `docker` at all?

# system setup

For reference, the system was broken by running the [fast footprint test](https://github.com/kata-containers/tests/pull/766), and was suffering from the [1000 containers](https://github.com/kata-containers/runtime/issues/807) issue.

```toml
[Meta]
  Version = "1.0.15"

[Runtime]
  Debug = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.2.1"
    Commit = "4969a31ceacea03a6047d25890c2bdf263c434b2"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  Msize9p = 8192
  Debug = false
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.3.0-rc1_agent_1ee972176ae.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67.11-137.container"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.2.1-728d45018f8e450c7c3cb6806dfcc57cb37fc1e1"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.2.1-f4a381251b8fd7d38e9fa92f122eca529c28208b"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.15.0-34-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2699A v4 @ 2.40GHz"
```
