### ISSUE TITLE
docker '-m' memory size maps oddly into container

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#933]
# Description of problem

We have [a test](https://github.com/kata-containers/tests/blob/master/metrics/density/memory_usage_inside_container.sh) that checks the size of the memory available inside a kata container. Recently in the metrics report generator I noticed that the '2G' memory test was reporting seeing '4G' inside the container. I'm pretty sure it used to report a little less than 2G... time to track that down.

# Expected result

I'd expect, when say requesting `-m 2G` on a container that I'd probably see 2G or memory, either allocated with some then used by kata, or a little more than 2G allocated to accommodate for any kata overhead and therefore leaving 2G free for the workload.

# Actual result

I ran a little script to check for a range of `-m` values:

```bash
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 1G ubuntu free -h
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           2.9G         41M        2.9G        8.1M         17M        2.9G
Swap:            0B          0B          0B
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 2G ubuntu free -h
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           3.9G         57M        3.9G        8.1M         16M        3.8G
Swap:            0B          0B          0B
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 4G ubuntu free -h
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           5.7G         87M        5.6G        8.0M         16M        5.6G
Swap:            0B          0B          0B
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 8G ubuntu free -h
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           5.7G        155M        5.5G        8.1M         17M        5.5G
Swap:            0B          0B          0B
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 16G ubuntu free -h
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           6.1G        285M        5.8G        8.2M         17M        5.7G
Swap:            0B          0B          0B
```

Which is odd - I'm not sure I even see the pattern there.... let's also get that as 'm'

```bash
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 1G ubuntu free -m
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           3019          43        2958           8          16        2934
Swap:             0           0           0
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 2G ubuntu free -m
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           4043          56        3969           8          17        3934
Swap:             0           0           0
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 4G ubuntu free -m
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           5579          89        5472           8          17        5426
Swap:             0           0           0
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 8G ubuntu free -m
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           5579         154        5408           8          16        5362
Swap:             0           0           0
+ for k in 1 2 4 8 16
+ docker run --rm -ti --runtime=kata-runtime -m 16G ubuntu free -m
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
              total        used        free      shared  buff/cache   available
Mem:           6091         282        5791           8          17        5742
Swap:             0           0           0

```

| reqested-G | tot-G | tot-M |
| --- | - | - |
| 1 | 2.9G | 3019 |
| 2 |3.9G | 4043 |
| 4 | 5.7G | 5579 |
| 8 | 5.7G | 5579 |
| 16 | 6.1G | 6091 |

## kata-env

```toml
[Meta]
  Version = "1.0.19"

[Runtime]
  Debug = false
  DisableNewNetNs = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.3.0"
    Commit = "780cd5f7b9d3c76522e96f83905b1ef224f8574d"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0 (v2.11.0-rc0-311-gc0647a6-dirty)\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-2018-11-21-14:43:11.797941016+0000-osbuilder-8fa94f9-agent-0f411fd"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67-17"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.3.0-7606e9e01642383b2da5da5510b765db89cf3c90"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.3.0-7816c4e1aafbc29eef8f92ed451814f35361e0e4"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.4.0-138-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz"

[Netmon]
  Version = "kata-netmon version 1.3.0"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```
